[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
eth_rpc_url = "https://polygon-mainnet.g.alchemy.com/v2/gGMIj1kDrkLdvjErjzKHDCZgI9CUhvob"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config